server:
  port: 8088

spring:
  application:
    name: dispatch-service
  redis:
    database: 0
    host: 39.98.65.135
    port: 6379
    password: 20200715
    lettuce:
      pool:
        #连接池最大连接数，负值表示无限制，默认8
        max-active: 8
        #连接池最大阻塞等待时间，负值表示无限制，默认-1
        max-wait: -1
        #连接池最大空闲连接，默认8
        max-idle: 8
        #连接池最小空闲连接，默认0
        min-idle: 0

baiduapi:
  ak: 7nt7ok0IOYiu8Zx2R1gKiUwhRMnHjrDy
  url: http://api.map.baidu.com

eureka:
  client:
    #表示是否将自己注册进EurekaServer,默认为true。
    register-with-eureka: true
    #是否从EurekaServer抓取已有的注册信息，默认为true。单节点无所谓，集群必须设置为true才能配合ribbon使用负载均衡
    fetchRegistry: true
    service-url:
      #单机版
      defaultZone: http://localhost:7001/eureka
      # 集群版
  #      defaultZone: http://eureka7001.com:7001/eureka,http://eureka7002.com:7002/eureka
  instance:
    instance-id: order-service
    #访问路径可以显示IP地址
    prefer-ip-address: true
    #Eureka客户端向服务端发送心跳的时间间隔，单位为秒(默认是30秒)
    #lease-renewal-interval-in-seconds: 1
    #Eureka服务端在收到最后一次心跳后等待时间上限，单位为秒(默认是90秒)，超时将剔除服务
    #lease-expiration-duration-in-seconds: 2